config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
  }

  get 'games/highscore'

  resources :games, except: [:edit, :update] do
    member do
      post 'create_storages'

      post 'buy_ingredients'
      post 'subscribe_ingredients'

      post 'end_month'

      post 'borrow_money'

      post 'force_change' if Rails.env.development?

      post 'hire'
      post 'advertise'
      post 'factory_assign'
      post 'factory_buyinstall'

      post 'contracts/cancel', to: 'contracts#cancel'
      post 'contracts/create', to: 'contracts#create'
    end

    resources :contracts, only: [:create]
  end

  resources :players, only: [:new, :create]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get 'admin', to: 'admin#index'

  root 'home#index'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @ogp = {
      title: "GenericFactoryGame is a resource-management and factory building game",
      description: %[As a factory owner, you have a factory that employees consume "generic" ingredients to produce "generic" products. You can sign some contracts with customers who need the products to be delivered, so that you can gain sales. It'll be the best to satisfy exact demands they require -- note that the demands change in certain months!],
    }
  end
end

app/views/home/index.html.erb
<p id="notice"><%= notice %></p>
<%- if alert %>
  <div class="alert alert-danger" role="alert">
    <%= alert %>
  </div>
<%- end %>

<div class="container-fluid bg-light p-5">
  <h1 class="display-4">GenericFactoryGame</h1>
  <p class="lead">
  GenericFactoryGame is a resource-management and factory building game.
  As a factory owner, you have a factory that employees consume "generic" ingredients to produce "generic" products. You can sign some contracts with customers who need the products to be delivered, so that you can gain sales.
  It'll be the best to satisfy exact demands they require -- note that the demands change in certain months!
  </p>

  <p class="lead">
  <small class="text-muted">
    GenericFactoryGameは資源管理・工場作成ゲームです。
    あなたは工場長として、従業員を用いて (一般的な)原料を加工し、(一般的な)商品を作っていきます。
    その商品を必要とする顧客に販売契約を結び、売上を得ていきましょう。
    商品生産と需要がぴったりあっていると最高です。ちなみに需要は月ごとに変動するので要注意です!
  </small>
  </p>

  <div class="container">
    <div class="row">
      <div class="col">
        <img src="images/generic-factory-game.png" title="GenericFactoryGame Logo" width="100%"/>
      </div>
      <div class="col">
        <img src="images/screenshot-1.0.0.png" title="GenericFactoryGame screenshot" width="100%"/>
      </div>
    </div>
  </div>

  <div align="right">
    Version <%= GenericFactoryGame::VERSION_MAJOR %>
    Released on <%= GenericFactoryGame::RELEASE_DATE %>
  </div>
  <div align="right">
    (<%= link_to 'Last updates', 'https://github.com/ujihisa/generic-factory-game/commits/master' %>)
  </div>

  <%- unless current_user %>
    <%= link_to 'Create a new player', new_player_path, class: 'btn btn-primary btn-lg', role: 'button' %>
    &nbsp;
  <%- end %>

  <%= link_to 'Start a new game', new_game_path, class: 'btn btn-secondary btn-lg', role: 'button' %>
  &nbsp;

  <%= link_to 'List saved games', games_path, class: 'btn btn-secondary btn-lg', role: 'button' %>
  &nbsp;

  <%= link_to 'High score', games_highscore_path, class: 'btn btn-secondary btn-lg', role: 'button' %>
</div>


<!--
<a href="https://gist.github.com/ujihisa/06ab65998f6db112fcb44928b3fd7608">(How to play in Japanese)</a>
-->