config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
  }

  get 'games/highscore'

  resources :games, except: [:edit, :update] do
    member do
      post 'create_storages'

      post 'buy_ingredients'
      post 'subscribe_ingredients'

      post 'end_month'

      post 'borrow_money'

      post 'force_change' if Rails.env.development?

      post 'hire'
      post 'advertise'
      post 'factory_assign'
      post 'factory_buyinstall'

      post 'contracts/cancel', to: 'contracts#cancel'
      post 'contracts/create', to: 'contracts#create'
    end

    resources :contracts, only: [:create]
  end

  resources :players, only: [:new, :create]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get 'admin', to: 'admin#index'

  root 'home#index'
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :game_with_user, only: [
    :create_storages, :buy_ingredients, :borrow_money, :subscribe_ingredients,
    :end_month, :hire, :factory_assign, :factory_buyinstall, :advertise,
  ]

  # GET /games
  # GET /games.json
  def index
    @current_games = Game.latest.where(
      version_major: GenericFactoryGame::VERSION_MAJOR,
      version_patch: GenericFactoryGame::VERSION_PATCH,
      mode: ['easy', 'normal']
    ).order(updated_at: :desc)

    @archived_games = Game.latest.where.not(
      version_major: GenericFactoryGame::VERSION_MAJOR,
      version_patch: GenericFactoryGame::VERSION_PATCH,
    ).order(version_major: :desc, updated_at: :desc)
  end

  def highscore
    @games = {
      'easy' => Game.best_games(GenericFactoryGame::VERSION_MAJOR, 'easy'),
      'normal' => Game.best_games(GenericFactoryGame::VERSION_MAJOR, 'normal'),
    }
    @old_games = Game.best_games(GenericFactoryGame::PREVIOUS_VERSION, 'normal')
  end

  # GET /games/1
  # GET /games/1.json
  def show
    @game = Game.find(params[:id])

    @estimate = Game.find(params[:id]).tap do |game|
      game.settlement()
    end

    @game_hint = @game.hint(@estimate)
    @ogp = {
      title: "#{@game.player.name}'s #{@game.mode} game (#{@game.status})",
      description: "Month $#{@game.month}K, Cash $#{@game.cash}K, Debt $#{@game.debt}K",
    }
  end

  # GET /games/new
  def new
    @game = Game.new
    @players = Player.all.reject(&:user)

    @world_best_scores = {
      easy: Game.where(
        version_major: GenericFactoryGame::VERSION_MAJOR,
        money: (1000..),
        mode: 'easy',
      ).order(month: :asc).limit(1).pick(:month),
      normal: Game.where(
        version_major: GenericFactoryGame::VERSION_MAJOR,
        money: (1000..),
        mode: 'normal'
      ).order(month: :asc).limit(1).pick(:month),
    }
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(
      version_major: GenericFactoryGame::VERSION_MAJOR,
      version_patch: GenericFactoryGame::VERSION_PATCH,
      ingredient_subscription: 0,
      **game_params)
    if @game.player.user && @game.player.user != current_user
      return redirect_to :new_game, alert: 'Invalid game/user'
    end

    case @game.mode
    when 'tutorial'
      @game.cash = 999
      @game.debt = 0
      @game.storage = 200
      @game.ingredient = 100
      @game.ingredient_subscription = 100
      @game.equipments = [Factory.lookup(equipment_name: :'Factory base')]
      @game.assignments = [Assignment.new(:produce, :Intermediate, 4)]
      @game.employee_groups_raw = {'Intermediate' => 4}.to_json
      @game.signed_contracts = {'Tutorial': -2}

      @game.messages = <<~EOS.lines.select(&:present?).to_a
        Welcome to GenericFactoryGame!
        In this tutorial I'd love you to understand "End month" before starting actual game.
        Try clicking random places and make sure the "End month" button does not show the red warning, and then click it. That's it!

        The goal of this game is to achieve 1 million dollars. ($1,000K)
      EOS
    when 'easy'
      @game.cash = 300
      @game.debt = 0
      @game.messages = ['You started your own business from nothing but $300K.']
    else # 'normal'
      @game.cash = 0
      @game.debt = 0
      @game.credit = 10
      @game.storage = 100
      @game.ingredient = 50
      @game.ingredient_subscription = 50
      @game.quality = 14
      @game.assignments = [
        Assignment.new(:produce, :Junior, 1),
        Assignment.new(:produce, :Intermediate, 1),
        Assignment.new(:produce, :Senior, 1),
      ]
      @game.employee_groups_raw = {
        'Junior' => 1,
        'Intermediate' => 1,
        'Senior' => 1,
      }.to_json
      @game.equipments = [
        Factory.lookup(equipment_name: :'Old factory base'),
      ]
      @game.signed_contracts = {'NormalA': -2}
    end
    @game.portfolios += [@game.portfolio]
    @players = Player.all.reject(&:user)

    if @game.save
      messages =
        if @game.mode == 'tutorial'
          @game.messages + <<~EOS.lines.to_a
            このチュートリアルではGenericFactoryGameの一部の振る舞いについて軽く触れて、ひとまず「End month」を完全に理解してもらいます。
            いろんなボタンを押したりしてみて、とにかく左下の"End month"のボタンの赤い警告をなくして、それからそれを押してみてください。それだけでいけるはずです!

            このゲームのクリア条件は、資産を$1,000Kにすることです。 (資産=現金-借金)
          EOS
        else
          @game.messages
        end
      redirect_to @game, alert: messages.join("\n")
    else
      redirect_to new_game_path, alert: messages.join("\n")
    end
  end

  def create_storages
    storage = params[:storage].to_i
    @game = Game.find(params[:id])

    diff = storage - @game.storage
    @game.cash -= diff / 100
    @game.storage = storage

    if diff <= 0
      redirect_to @game, alert: "[ERROR] Missing storage"
    elsif 0 <= @game.cash && @game.save
      redirect_to @game, notice: "Successfully Bought #{diff}t Storages"
    else
      redirect_to @game, alert: "Failed to buy Storages: #{@game.errors.messages}"
    end
  end

  def buy_ingredients
    vol = params[:vol].to_i
    @game = Game.find(params[:id])
    @game.cash -= vol * 0.25
    @game.ingredient += vol
    if 0 <= @game.cash && @game.save
      redirect_to @game, notice: "Successfully Bought #{vol}t Ingredients"
    else
      redirect_to @game, alert: "Failed to buy Ingredients"
    end
  end

  def subscribe_ingredients
    if @game.credit < 10
      return redirect_to @game, alert: 'Not enough credit!'
    end

    before = @game.ingredient_subscription.to_i
    after = params[:ingredient_subscription].to_i

    change_fee = [(after - before) * 0.1, 0].max
    @game.cash -= change_fee
    @game.ingredient_subscription = after

    if 0 <= @game.cash && @game.save
      if 0 < before
        redirect_to @game, notice: "Successfully changed subscription to #{after - before}t Ingredients"
      else
        redirect_to @game, notice: "Successfully Subscribed #{after}t Ingredients"
      end
    else
      redirect_to @game, alert: "Failed to Subscribed Ingredients"
    end
  end

  def end_month
    @game = Game.find(params[:id])

    @game.settlement()

    if @game.save
      if @game.cash < 0
        redirect_to @game, notice: 'Game over!'
      elsif 1000 <= @game.money
        redirect_to @game, notice: 'Game clear!'
      elsif @game.month % 12 == 0
        redirect_to @game, alert: "It's #{2020 + @game.month / 12}. Happy new year!"
      else
        redirect_to @game
      end
    else
      redirect_to @game, alert: "Hmm. something was wrong... #{@game.errors.messages}"
    end
  end

  def borrow_money
    new_debt = params[:debt].to_i

    # This validation can't be in game model, since this is only when to borrow money
    if @game.max_debt < new_debt
      return redirect_to @game, alert: "You can't borrow cash more than your credit * 10"
    end

    @game.cash += new_debt - @game.debt
    @game.debt = new_debt

    if @game.cash < 0
      return redirect_to @game, alert: "Not enough cash"
    end

    if @game.save
      redirect_to @game, notice: 'Borrow/Pay succeeded'
    else
      redirect_to @game, alert: 'Borrow/Pay failed'
    end
  end

  def hire
    # num_employees: {"Junior"=>2, "Intermediate"=>0, "Senior"=>0}
    num_employees = JSON.parse(params[:num_employees_json])

    num_paid =
      @game.organization_hire(
        num_employees.to_h {|k, v| [k.to_sym, v.to_i] })
    if @game.save
      redirect_to @game, notice: "Successfully hired employees. Paid $#{num_paid}K for recruiting them."
    else
      redirect_to @game, alert: "Failed to hire: #{@game.errors.messages}"
    end
  end

  def factory_assign
    # num_role_diffs_json: {"Junior":{"produce":0,"mentor":0}}
    num_role_diffs = JSON.parse(params[:num_role_diffs_json])
    num_role_diffs.each do |eg_name, diffs|
      @game.factory_assign_add(eg_name.to_sym, **diffs.to_h { [_1.to_sym, _2.to_i] })
    end
    if @game.save
      redirect_to @game, notice: 'Successfully assigned tasks'
    else
      redirect_to @game, alert: "Failed to assign: #{@game.errors.messages}"
    end
  end

  def factory_buyinstall
    equipment = Factory.lookup(equipment_name: params[:equipmentRadios])
    return redirect_to @game, alert: "Invalid equipment_name #{params[:equipmentRadios]}" unless equipment

    @game.buyinstall_equipment(equipment)
    if @game.cash < 0
      redirect_to @game, alert: 'Not enough money'
    elsif @game.save
      redirect_to @game, notice: "#{params[:equipmentRadios]} has been installed into your factory."
    else
      redirect_to @game, alert: "#{@game.errors.messages}"
    end
  end

  if Rails.env.development?
    def force_change
      @game = Game.find(params[:id])
      if @game.update(params.permit(:cash, :debt, :credit, :storage, :product, :quality, :ingredient))
        redirect_to @game, notice: 'GOOD GOOD'
      else
        redirect_to @game, alert: "#{@game.errors.messages}"
      end
    end
  end

  private def game_with_user
    @game = Game.latest.find(params[:id])

    if @game.player.user && @game.player.user != current_user
      redirect_to :new_game, alert: 'Invalid game/user'
    end
  end

  private def game_params
    params.require(:game).permit(:player_id, :mode)
  end

  def advertise
    if @game.credit < 10
      return redirect_to @game, alert: 'Not enough credit to advertise'
    end

    @game.cash -= 80

    if @game.cash < 0
      return redirect_to @game, alert: 'Not enough cash to advertise'
    end

    if @game.advertising
      return redirect_to @game, alert: "You can't advertise more than once a month"
    end

    @game.advertising = true
    if @game.save
      redirect_to @game, notice: "You succeeded in advertizing yourself in this month."
    else
      redirect_to @game, alert: "Failed to advertise. #{@game.errors.messages}"
    end
  end
end

app/views/games/_charts.html.erb
<%- if @game.portfolios.present? %>
  <canvas id="chartMoney"></canvas>
  <script>
    var ctx = document.getElementById('chartMoney').getContext('2d');
    var chartMoney = new Chart(ctx, {
      type: 'line',
      data: {
        labels: <%= @game.portfolios.map { _1['month'] }.inspect %>,
        datasets: [
          {
            label: 'Debt',
            data: <%= @game.portfolios.map { -_1['debt'] }.inspect %>,
            backgroundColor: [
              'rgba(255, 99, 132, 0.2)',
            ],
            borderColor: [
              'rgba(255, 99, 132, 1)',
            ],
            borderWidth: 1,
            lineTension: 0,
          },
          {
            label: 'Cash',
            data: <%= @game.portfolios.map { _1['cash'] }.inspect %>,
            backgroundColor: [
              'rgba(54, 162, 235, 0.2)',
            ],
            borderColor: [
              'rgba(54, 162, 235, 1)',
            ],
            borderWidth: 1,
            lineTension: 0,
          },
          {
            label: 'Money',
            data: <%= @game.portfolios.map { _1['cash'] - _1['debt'] }.inspect %>,
            fill: false,
            borderColor: [
              'rgba(27, 81, 117, 1)',
            ],
            borderWidth: 2,
            lineTension: 0,
          },
        ]
      },
      options: {
        scales: {
          yAxes: [{
            // stacked: true,
            ticks: {
              beginAtZero: true,
            }
          }]
        }
      }
    });
  </script>
<%- end %>

app/views/games/new.html.erb
<%- if alert %>
  <div class="alert alert-danger" role="alert">
    <%= alert %>
  </div>
<%- end %>

<% if @game.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

    <ul>
      <% @game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>


<div class="field">
  <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center" style='max-width: 700px'>
    <h1 class="display-4">Start a new game</h1>
    <%- if current_user %>
      <p class="lead">Choose the game difficulty</p>
    <%- end %>
  </div>

  <%- if current_user %>
    <%- player = current_user.player %>
    <div class="container" style='max-width: 960px;'>
      <div class="card-deck mb-3">
        <!-- Tutorial -->
        <div class="card mb-4 shadow-sm" style='min-width: 220px;'>
          <div class="card-header">
            <h4 class="my-0 font-weight-normal">Tutorial <%= player.best_game('tutorial') ? '✔️' : '' %></h4>
          </div>
          <div class="card-body">
            <%= form_with(model: @game, local: true) do |form| %>
              <%= hidden_field_tag :'game[player_id]', player.id %>
              <%= hidden_field_tag :'game[mode]', 'tutorial' %>
              <%= form.submit "Try tutorial", class: 'btn btn-lg btn-secondary' %>
            <% end %>
            <p></p>

            <p class="card-text">
              If it's first time coming here, try this first!
            </p>
            <p>
              Many features are locked. Please use this to learn about the UI and the basics of the game.
            </p>
            <ul>
              <li>Initial money: $999K</li>
              <li>Goal: $1000K</li>
              <li>Start from nothing: false</li>
              <li>Usually it takes between 1sec to 1min</li>
            </ul>
          </div>
        </div>
        <!-- Easy -->
        <div class="card mb-4 shadow-sm" style='min-width: 220px;'>
          <div class="card-header">
            <h4 class="my-0 font-weight-normal">Easy</h4>
          </div>
          <div class="card-body">
            <%= form_with(model: @game, local: true) do |form| %>
              <%= hidden_field_tag :'game[player_id]', player.id %>
              <%= hidden_field_tag :'game[mode]', 'easy' %>
              <%= form.submit "Start game", class: 'btn btn-lg btn-block btn-primary' %>
            <% end %>

            <p>
            <%- if best_game = player.best_game('easy') %>
              Your best score: <%= best_game.month %> months
            <%- elsif player.games.empty? %>
              First time to try!
            <%- else %>
              <%= link_to 'Working in progress', games_path %>
            <%- end %>
            </p>

            <p class="card-text">
              The main game, but this is a lot easier. Use this difficulty setting to understand the game system!
            </p>
            <ul>
              <li>Initial money: $300K</li>
              <li>Goal: $1000K</li>
              <li>Start from nothing: true</li>
              <li>Usually it takes between 3mins to 5mins</li>
            </ul>
          </div>
        </div>
        <!-- Normal -->
        <div class="card mb-4 shadow-sm" style='min-width: 220px;'>
          <div class="card-header">
            <h4 class="my-0 font-weight-normal">Normal</h4>
          </div>
          <div class="card-body">
            <%= form_with(model: @game, local: true) do |form| %>
              <%= hidden_field_tag :'game[player_id]', player.id %>
              <%= hidden_field_tag :'game[mode]', 'normal' %>
              <%= form.submit "Start game", class: 'btn btn-lg btn-block btn-primary' %>
            <% end %>

            <p>
            <%- if best_game = player.best_game('normal') %>
              Your best score: <%= best_game.month %> months
            <%- elsif player.games.empty? %>
              First time to try!
            <%- else %>
              <%= link_to 'Working in progress', games_path %>
            <%- end %>
            </p>
            <p>World best score: <%= @world_best_scores[:normal] || 'N/A' %> months</p>

            <p class="card-text">
              The main game. Not too hard to play but can be challenging if you'd like to achieve a higher score.
            </p>
            <ul>
              <li>Initial money: $0K</li>
              <li>Goal: $1000K</li>
              <li>Start from nothing: false</li>
              <li>Usually it takes between 5mins to 10mins</li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  <%- else %>
    <div class="alert alert-danger" role="alert">
      You aren't logged in.
    </div>
    <div class="container" style='max-width: 960px;'>
      <div class="card-deck mb-3 text-center">
        <%- @players.each_slice(3).each do |players| %>
          <%- players[2] ||= nil # To expand always to 3 %>
          <%- players.each do |player| %>
            <div class="card mb-4 shadow-sm" style='min-width: 220px;'>
              <%- if player %>
                <div class="card-header">
                  <h4 class="my-0 font-weight-normal"><%= player.name %></h4>
                </div>
                <div class="card-body">
                  <div>
                    <strong>
                      <%= link_to 'Sign up', new_user_registration_path(player_id: player.id) %>
                    </strong>
                  </div>
                  <br/>

                </div>
              <%- end %>
            </div>
          <%- end %>
          <br/>
        <%- end %>
      </div>
    </div>
  <%- end %>
</div>
<div class="alert alert-info" role="alert">
  Didn't find your own player? Try creating a player for you! <%= link_to new_player_url, new_player_path %>
</div>

</div></div>

app/views/games/show.html.erb
<%- case @game.status %>
<%- when :game_over %>
  <h1 class='display-3 container-fluid bg-light p-5'>
    <font color=red>
      💸💀💸 GAME OVER
    </font>
  </h1>
  <%- if @game.mode == 'tutorial' %>
    <div class="container" style='max-width: 480px;'>
      <div class="card-deck mb-3 text-center">
        <div class="card mb-4 shadow-sm" style='min-width: 220px;'>
          <div class="card-header">
            <h4 class="my-0 font-weight-normal">
              Let's try again
            </h4>
          </div>
          <div class="card-body">
            <%= form_with(url: games_path, method: :post) do |form| %>
              <%= hidden_field_tag :'game[player_id]', @game.player.id %>
              <%= hidden_field_tag :'game[mode]', 'tutorial' %>
              <%= form.submit "Start game (Tutorial)", class: 'btn btn-lg btn-block btn-secondary' %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <hr />
  <%- elsif 3 <= @game.month %>
    <%= render 'stats' %>
  <%- else %>
    <div class="alert alert-primary" role="alert">
      (Charts will be shown here if you survive longer than 3 months.)
    </div>
  <%- end %>
<%- when :completed %>
  <h1 class='display-3 container-fluid bg-light p-5'>
    🎉 Game Clear!
  </h1>

  <%- case @game.mode %>
  <%- when 'tutorial' %>
    <div class="container" style='max-width: 480px;'>
      <div class="card-deck mb-3 text-center">
        <div class="card mb-4 shadow-sm" style='min-width: 220px;'>
          <div class="card-header">
            <h4 class="my-0 font-weight-normal">
              Let's try an actual game!
            </h4>
          </div>
          <div class="card-body">
            <%= form_with(url: games_path, method: :post) do |form| %>
              <%= hidden_field_tag :'game[player_id]', @game.player.id %>
              <%= hidden_field_tag :'game[mode]', 'easy' %>
              <%= form.submit "Start game (EASY MODE)", class: 'btn btn-lg btn-block btn-primary' %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <hr />
  <%- when 'easy' %>
    <%- if @game.player.user == current_user %>
      <div class="container" style='max-width: 480px;'>
        <div class="card-deck mb-3 text-center">
          <div class="card mb-4 shadow-sm" style='min-width: 220px;'>
            <div class="card-header">
              <h4 class="my-0 font-weight-normal">
                Let's try normal mode
              </h4>
            </div>
            <div class="card-body">
              <%= form_with(url: games_path, method: :post) do |form| %>
                <%= hidden_field_tag :'game[player_id]', @game.player.id %>
                <%= hidden_field_tag :'game[mode]', 'normal' %>
                <%= form.submit "Start game (Normal)", class: 'btn btn-lg btn-block btn-primary' %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    <%- end %>
    <%= render 'stats' %>
    <hr />
  <%- else # normal %>
    <%- if current_user && current_user.player.completed?(@game.version_major, 'normal') %>
      <%= render 'stats' %>
    <%- else %>
      You can see the stats details only if you complete a <%= @game.version %> normal game!
    <%- end %>
  <%- end %>
<%- end %>


<div class="row">
  <div class="col-md-9 themed-grid-col">
    <%#= react_component('GamePane', {
      status: @game.status,
      cash: @game.cash,
      debt: @game.debt,
      credit: @game.credit,
      storage: @game.storage,
      ingredientSubscription: @game.ingredient_subscription,
      action: borrow_money_game_url,
      formAuthenticityToken: form_authenticity_token,
      subscribe_ingredients_game_url: subscribe_ingredients_game_url,
      end_month_game_url: end_month_game_url,
      estimate_status: @estimate.status,
      create_storages_game_url: create_storages_game_url,
      month: @game.month,
      ingredient: @game.ingredient,
      product: @game.product,
      quality: @game.quality,
      createContractUrl: contracts_create_game_path(@game.id),
      cancelContractUrl: contracts_cancel_game_path(@game.id),
      contractDump: Contract.dump(@game.mode),
      signedContracts: @game.signed_contracts.as_json,
      buy_ingredients_game_url: buy_ingredients_game_url,
      notice: notice,
      alert: alert,
      productionVolume: @game.capped_production,
      productionQuality: @game.factory.production_quality,
      equipments: @game.equipments,
      employees: Assignment.employee_groups_with_num_hired(@game.assignments),
      employeeGroups: @game.employee_groups,
      hire_game_path: hire_game_path,
      factory_assign_game_path: factory_assign_game_path,
      factory_buyinstall_game_path: factory_buyinstall_game_path,
      advertise_game_path: advertise_game_path,
      productRequiredNextMonth: @game.signed_contracts.product_required(@game.next_month),
      allEquipments: Factory::EQUIPMENTS.select {|_, v| v[:modes].include?(@game.mode) },
      assignmentsSummary: EmployeeGroup::ALL.values.map(&:category).uniq.map {|category|
        {
          name: category,
          numRoles: {
            produce: @game.assignments.select { _1.employee_group.category == category && _1.role == :produce }.sum(&:num),
            mentor: @game.assignments.select { _1.employee_group.category == category && _1.role == :mentor }.sum(&:num),
            # kaizen: @game.assignments.select { _1.employee_group.category == category && _1.role == :kaizen }.sum(&:num),
          }
        }
      },
      minCashForNextMonth: -@estimate.cash,
      mode: @game.mode,
      darklaunch: {
        'enable-bank-client-side-adjuetment-buttons': Darklaunch.v1_variation('enable-bank-client-side-adjuetment-buttons', @game.player),
      },
      # assignmentsSummary: @game.assignments.each_with_object([]) {|a, memo|
      #   if x = memo.find {|x| x[:name] == a.employee_group_name }
      #     x[:numRoles][a.role] = a.num
      #   else
      #     memo << { name: a.employee_group_name, numRoles: { a.role => a.num } }
      #   end
      # }.sort_by { [:Junior, :Intermediate, :Senior].index(_1[:name]) }
    }) %>

    <%- if Rails.env.development? %>
      <%- if @game_hint %>
        <h2>Game hint</h5>
        <div>
            <p><%= @game_hint[:fact] %></p>
            <p><%= @game_hint[:suggestion] %></p>
        </div>
      <%- end %>
    <%- end %>
  </div>
  <div class="col-md-3 themed-grid-col">
  <h2>Calendar</h2>
  <h5><%= @game.current_month %> <%= 2020 + @game.month / 12 %> result</h5>
  <ul>
    <%- @game.alerts.each do |alert| %>
      <li class="alert alert-danger" role="alert"/><%= alert %>
    <%- end %>
    <%- @game.messages.each do |message| %>
      <li /><%= message %>
    <%- end %>
  </ul>
  <h5><%= @estimate.current_month %> <%= 2020 + @estimate.month / 12 %> estimate</h5>
  <ul>
    <%- @estimate.alerts.each do |alert| %>
      <li class="alert alert-danger" role="alert"/><%= alert %>
    <%- end %>
    <%- @estimate.messages.each do |message| %>
      <li class="text-muted"/><%= message %>
    <%- end %>
  </ul>

  <hr>
  <%- if notice %>
    <p id="notice">
    🆕
    <%= notice %>
    </p>
  <%- end %>

      <h3>Factory</h3>
      <!--
        Estimated Ingredients Consumption: <%= @game.factory.production_volume / Game::INGREDIENT2PRODUCT %>t
        <%- if @game.factory.production_volume != @game.capped_production %>
          <ul>
            <li><font color=red>(Capped to <%= @game.capped_production / Game::INGREDIENT2PRODUCT %>t, because you don't have much ingredients!)</font>
          </ul>
        <%- end %>
      -->
      Estimated Product Generation: <%= @game.factory.production_volume %>t
      <%- if @game.factory.production_volume != @game.capped_production %>
        <ul>
          <li><font color=red>(Capped to <%= @game.capped_production %>t, because you don't have enough ingredients!)</font>
        </ul>
      <%- end %>
      <br/>
  </div>
</div>
<%- if Rails.env.development? %>
  <hr>
  <div align="right">
    <h2>DEVELOPMENT</h2>
    <%= form_with(url: force_change_game_url, method: 'post') do |form| %>
      Cash: <%= form.text_field :cash, value: @game.cash %><br/>
      Money: <%= form.text_field :money, value: @game.money %><br/>
      Credit: <%= form.text_field :credit, value: @game.credit %><br/>
      Storage: <%= form.text_field :storage, value: @game.storage %><br/>
      Product: <%= form.text_field :product, value: @game.product %><br/>
      Quality: <%= form.text_field :quality, value: @game.quality %><br/>
      Ingredient: <%= form.text_field :ingredient, value: @game.ingredient %><br/>
      <%= form.submit %>
    <%- end %>
  </div>
  <dl>
    <dd>Assignments:</dd>
    <dt><code><%= @game.assignments_raw %></code></dt>

    <dd>Employee groups:</dd>
    <dt><code><%= @game.employee_groups_raw %></code></dt>
  </dl>
<%- end %>